version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXP=${JWT_EXP}
      - MONGO_DB_URI=${MONGO_DB_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
